### ISSUE TITLE
Option to activate env using virtphp

### ISSUE THREAD

**Issue by InFog** [virtphp/virtphp#59]
It would be great to have an option to activate the env using something like this:

virtphp activate EpisodeIV

**Comment by jakerella** [comment]
Yes, yes it would. :)

@jwoodcock has been looking into this for a while now, and unfortunately, our current thinking is that it isn't possible. The issue is that we have to interact with your terminal shell session, and we can't really do that without hijacking your entire shell, something we're not comfortable doing. I'll let Jacques add any additional details as he's the one that's looked into it.

**Comment by InFog** [comment]
Yes, I tried some hacks here and it didn't work, since when we call commands from within PHP it uses a new shell environment.

I'm using Python's virtualenv for a while now and there we also need to source a file to activate the env.

Well, if I find something useful I'll let you guys know about it :)

**Comment by ramsey** [comment]
Thanks for the suggestion, @InFog. I've been looking at the source code for phpbrew and thinking through ways to refactor VirtPHP accordingly. I hope to have time in the near future to devote to making a proof-of-concept refactoring that I can submit for review in a pull request.

**Comment by jwoodcock** [comment]
@InFog so virtualenvwrapper allows you to do this by having you source a pre-file on each shell-session start. This dumps a TON of functions into your session that you can use, including an activate command. 

virtualenv actually has the same issue we have. In order to source a file using just virtualenv, you have to provide a full path. 

For us, I found a way to simplify the activation process and have submitted PR #57, we're just bad at finishing reviews apparently- *cough cough @ramsey @jakerella. This updated functionality will allow you to type `virtphp activate myenv` and do two things. 1) if you have a compatible clipboard, copy the source command to it which you can just paste and it will activate the environment. 2) Output the source command with full environment path so all you have to do it copy and paste. 

For now, that's the best we can do. I'll be interested to see what @ramsey comes up with in his refactoring, but whatever it is, it'll depend on dumping functions into the shell session.

**Comment by InFog** [comment]
#57 is not bad at all. I mean, it's a good option and I would like to use it :+1:

**Comment by ramsey** [comment]
Like I said, everyone should take a look at how phpbrew does this. They do it in a really smart way. It's what I'd like to do, but it will require a full refactor, I think.

**Comment by jwoodcock** [comment]
Any chance of the cliff notes?

Jacques Woodcock
jacques@kitewebconsulting.com
615-293-0328

**Comment by ramsey** [comment]
Not today. Maybe I can write up something later this week.d

**Comment by jwoodcock** [comment]
so what are we waiting on to get the #57 approved?

**Comment by jakerella** [comment]
@jwoodcock Just reviewed, only one real suggested change, then nit-picky stuff.

**Comment by ramsey** [comment]
Nothing, I guess. I was going to try to take a stab at a PR refactoring, as I said, but I haven't had time. Since I'm moving so slow on that, we should go ahead and just accept #57.

**Comment by jwoodcock** [comment]
Just saw Jordan's notes. Will review and get an updated PR.

**Comment by InFog** [comment]
Nice! So I think this issue can be closed, since all the work is being done in #57 :)

Thanks, people!
